namespace Payroll.Application.Settings;

public sealed record SettingOptionDto(
    Guid OptionId,
    string Name);

public sealed record PayrollPreviewHelpOptionDto(
    string Code,
    string Label,
    bool IsEnabled,
    string HelpText);

public sealed record PayrollSettingsDto(
    string CompanyAddress,
    string AppFontFamily,
    decimal AppFontSize,
    string AppTextColorHex,
    string AppMutedTextColorHex,
    string AppBackgroundColorHex,
    string AppAccentColorHex,
    string AppLogoText,
    string AppLogoPath,
    string PrintFontFamily,
    decimal PrintFontSize,
    string PrintTextColorHex,
    string PrintMutedTextColorHex,
    string PrintAccentColorHex,
    string PrintLogoText,
    string PrintLogoPath,
    string PrintTemplate,
    string DecimalSeparator,
    string ThousandsSeparator,
    string CurrencyCode,
    decimal? NightSupplementRate,
    decimal? SundaySupplementRate,
    decimal? HolidaySupplementRate,
    decimal AhvIvEoRate,
    decimal AlvRate,
    decimal SicknessAccidentInsuranceRate,
    decimal TrainingAndHolidayRate,
    decimal VacationCompensationRate,
    decimal VacationCompensationRateAge50Plus,
    decimal VehiclePauschalzone1RateChf,
    decimal VehiclePauschalzone2RateChf,
    decimal VehicleRegiezone1RateChf,
    IReadOnlyCollection<PayrollPreviewHelpOptionDto> PayrollPreviewHelpOptions,
    IReadOnlyCollection<SettingOptionDto> Departments,
    IReadOnlyCollection<SettingOptionDto> EmploymentCategories,
    IReadOnlyCollection<SettingOptionDto> EmploymentLocations,
    Guid? CurrentGeneralSettingsVersionId = null,
    DateOnly GeneralSettingsValidFrom = default,
    DateOnly? GeneralSettingsValidTo = null,
    IReadOnlyCollection<PayrollGeneralSettingsVersionDto>? GeneralSettingsHistory = null,
    Guid? CurrentHourlySettingsVersionId = null,
    DateOnly HourlySettingsValidFrom = default,
    DateOnly? HourlySettingsValidTo = null,
    IReadOnlyCollection<PayrollHourlySettingsVersionDto>? HourlySettingsHistory = null,
    Guid? CurrentMonthlySalarySettingsVersionId = null,
    DateOnly MonthlySalarySettingsValidFrom = default,
    DateOnly? MonthlySalarySettingsValidTo = null,
    IReadOnlyCollection<PayrollMonthlySalarySettingsVersionDto>? MonthlySalarySettingsHistory = null,
    decimal AppPagePadding = 20m,
    decimal AppPanelPadding = 12m,
    decimal AppSectionSpacing = 12m,
    decimal AppPanelCornerRadius = 8m,
    decimal AppTableCellVerticalPadding = 6m);

public sealed record PayrollGeneralSettingsVersionDto(
    Guid VersionId,
    DateOnly ValidFrom,
    DateOnly? ValidTo,
    decimal AhvIvEoRate,
    decimal AlvRate,
    decimal SicknessAccidentInsuranceRate,
    decimal TrainingAndHolidayRate,
    bool IsCurrent);

public sealed record PayrollHourlySettingsVersionDto(
    Guid VersionId,
    DateOnly ValidFrom,
    DateOnly? ValidTo,
    decimal? NightSupplementRate,
    decimal? SundaySupplementRate,
    decimal? HolidaySupplementRate,
    decimal VacationCompensationRate,
    decimal VacationCompensationRateAge50Plus,
    decimal VehiclePauschalzone1RateChf,
    decimal VehiclePauschalzone2RateChf,
    decimal VehicleRegiezone1RateChf,
    bool IsCurrent);

public sealed record PayrollMonthlySalarySettingsVersionDto(
    Guid VersionId,
    DateOnly ValidFrom,
    DateOnly? ValidTo,
    bool IsCurrent);

public sealed record SavePayrollSettingsCommand(
    string CompanyAddress,
    string AppFontFamily,
    decimal AppFontSize,
    string AppTextColorHex,
    string AppMutedTextColorHex,
    string AppBackgroundColorHex,
    string AppAccentColorHex,
    string AppLogoText,
    string AppLogoPath,
    string PrintFontFamily,
    decimal PrintFontSize,
    string PrintTextColorHex,
    string PrintMutedTextColorHex,
    string PrintAccentColorHex,
    string PrintLogoText,
    string PrintLogoPath,
    string PrintTemplate,
    string DecimalSeparator,
    string ThousandsSeparator,
    string CurrencyCode,
    decimal? NightSupplementRate,
    decimal? SundaySupplementRate,
    decimal? HolidaySupplementRate,
    decimal AhvIvEoRate,
    decimal AlvRate,
    decimal SicknessAccidentInsuranceRate,
    decimal TrainingAndHolidayRate,
    decimal VacationCompensationRate,
    decimal VacationCompensationRateAge50Plus,
    decimal VehiclePauschalzone1RateChf,
    decimal VehiclePauschalzone2RateChf,
    decimal VehicleRegiezone1RateChf,
    IReadOnlyCollection<PayrollPreviewHelpOptionDto> PayrollPreviewHelpOptions,
    IReadOnlyCollection<SettingOptionDto> Departments,
    IReadOnlyCollection<SettingOptionDto> EmploymentCategories,
    IReadOnlyCollection<SettingOptionDto> EmploymentLocations,
    Guid? EditingGeneralSettingsVersionId = null,
    DateOnly GeneralSettingsValidFrom = default,
    DateOnly? GeneralSettingsValidTo = null,
    Guid? EditingHourlySettingsVersionId = null,
    DateOnly HourlySettingsValidFrom = default,
    DateOnly? HourlySettingsValidTo = null,
    Guid? EditingMonthlySalarySettingsVersionId = null,
    DateOnly MonthlySalarySettingsValidFrom = default,
    DateOnly? MonthlySalarySettingsValidTo = null,
    decimal AppPagePadding = 20m,
    decimal AppPanelPadding = 12m,
    decimal AppSectionSpacing = 12m,
    decimal AppPanelCornerRadius = 8m,
    decimal AppTableCellVerticalPadding = 6m);
