namespace Payroll.Application.Settings;

public sealed record SettingOptionDto(
    Guid OptionId,
    string Name);

public sealed record PayrollPreviewHelpOptionDto(
    string Code,
    string Label,
    bool IsEnabled,
    string HelpText);

public sealed record PayrollSettingsDto(
    string CompanyAddress,
    string AppFontFamily,
    decimal AppFontSize,
    string AppTextColorHex,
    string AppMutedTextColorHex,
    string AppBackgroundColorHex,
    string AppAccentColorHex,
    string AppLogoText,
    string AppLogoPath,
    string PrintFontFamily,
    decimal PrintFontSize,
    string PrintTextColorHex,
    string PrintMutedTextColorHex,
    string PrintAccentColorHex,
    string PrintLogoText,
    string PrintLogoPath,
    string PrintTemplate,
    string DecimalSeparator,
    decimal? NightSupplementRate,
    decimal? SundaySupplementRate,
    decimal? HolidaySupplementRate,
    decimal AhvIvEoRate,
    decimal AlvRate,
    decimal SicknessAccidentInsuranceRate,
    decimal TrainingAndHolidayRate,
    decimal VacationCompensationRate,
    decimal VacationCompensationRateAge50Plus,
    decimal VehiclePauschalzone1RateChf,
    decimal VehiclePauschalzone2RateChf,
    decimal VehicleRegiezone1RateChf,
    IReadOnlyCollection<PayrollPreviewHelpOptionDto> PayrollPreviewHelpOptions,
    IReadOnlyCollection<SettingOptionDto> Departments,
    IReadOnlyCollection<SettingOptionDto> EmploymentCategories,
    IReadOnlyCollection<SettingOptionDto> EmploymentLocations);

public sealed record SavePayrollSettingsCommand(
    string CompanyAddress,
    string AppFontFamily,
    decimal AppFontSize,
    string AppTextColorHex,
    string AppMutedTextColorHex,
    string AppBackgroundColorHex,
    string AppAccentColorHex,
    string AppLogoText,
    string AppLogoPath,
    string PrintFontFamily,
    decimal PrintFontSize,
    string PrintTextColorHex,
    string PrintMutedTextColorHex,
    string PrintAccentColorHex,
    string PrintLogoText,
    string PrintLogoPath,
    string PrintTemplate,
    string DecimalSeparator,
    decimal? NightSupplementRate,
    decimal? SundaySupplementRate,
    decimal? HolidaySupplementRate,
    decimal AhvIvEoRate,
    decimal AlvRate,
    decimal SicknessAccidentInsuranceRate,
    decimal TrainingAndHolidayRate,
    decimal VacationCompensationRate,
    decimal VacationCompensationRateAge50Plus,
    decimal VehiclePauschalzone1RateChf,
    decimal VehiclePauschalzone2RateChf,
    decimal VehicleRegiezone1RateChf,
    IReadOnlyCollection<PayrollPreviewHelpOptionDto> PayrollPreviewHelpOptions,
    IReadOnlyCollection<SettingOptionDto> Departments,
    IReadOnlyCollection<SettingOptionDto> EmploymentCategories,
    IReadOnlyCollection<SettingOptionDto> EmploymentLocations);
