using Payroll.Domain.Employees;

namespace Payroll.Application.Employees;

public sealed record EmployeeListQuery(
    string? SearchText,
    bool? IsActive);

public sealed record EmployeeListItemDto(
    Guid EmployeeId,
    string PersonnelNumber,
    string FullName,
    bool IsActive,
    string? City,
    string? Country,
    string? Email,
    string? DepartmentName,
    string? EmploymentCategoryName,
    string? EmploymentLocationName,
    decimal HourlyRateChf,
    decimal MonthlyBvgDeductionChf,
    DateOnly ContractValidFrom,
    DateOnly? ContractValidTo);

public sealed record EmployeeDetailsDto(
    Guid EmployeeId,
    string PersonnelNumber,
    string FirstName,
    string LastName,
    DateOnly? BirthDate,
    DateOnly EntryDate,
    DateOnly? ExitDate,
    bool IsActive,
    string Street,
    string? HouseNumber,
    string? AddressLine2,
    string PostalCode,
    string City,
    string Country,
    string? ResidenceCountry,
    string? Nationality,
    string? PermitCode,
    string? TaxStatus,
    bool? IsSubjectToWithholdingTax,
    string? AhvNumber,
    string? Iban,
    string? PhoneNumber,
    string? Email,
    Guid? DepartmentOptionId,
    string? DepartmentName,
    Guid? EmploymentCategoryOptionId,
    string? EmploymentCategoryName,
    Guid? EmploymentLocationOptionId,
    string? EmploymentLocationName,
    EmployeeWageType WageType,
    Guid? CurrentContractId,
    DateOnly ContractValidFrom,
    DateOnly? ContractValidTo,
    decimal HourlyRateChf,
    decimal MonthlyBvgDeductionChf,
    decimal SpecialSupplementRateChf,
    IReadOnlyCollection<EmploymentContractVersionDto> ContractHistory);

public sealed record EmploymentContractVersionDto(
    Guid ContractId,
    DateOnly ValidFrom,
    DateOnly? ValidTo,
    decimal HourlyRateChf,
    decimal MonthlyBvgDeductionChf,
    decimal SpecialSupplementRateChf,
    bool IsCurrent);

public sealed record SaveEmployeeCommand(
    Guid? EmployeeId,
    string PersonnelNumber,
    string FirstName,
    string LastName,
    DateOnly? BirthDate,
    DateOnly EntryDate,
    DateOnly? ExitDate,
    bool IsActive,
    string Street,
    string? HouseNumber,
    string? AddressLine2,
    string PostalCode,
    string City,
    string Country,
    string? ResidenceCountry,
    string? Nationality,
    string? PermitCode,
    string? TaxStatus,
    bool? IsSubjectToWithholdingTax,
    string? AhvNumber,
    string? Iban,
    string? PhoneNumber,
    string? Email,
    Guid? DepartmentOptionId,
    Guid? EmploymentCategoryOptionId,
    Guid? EmploymentLocationOptionId,
    EmployeeWageType WageType,
    Guid? EditingContractId,
    DateOnly ContractValidFrom,
    DateOnly? ContractValidTo,
    decimal HourlyRateChf,
    decimal MonthlyBvgDeductionChf,
    decimal SpecialSupplementRateChf);
